In [3]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=A+B
print('Addition:\n',C,'\n\n')
D=A-B
print('Subtraction:\n',D,'\n\n')
#multiplication element-wise
E=A*B
print('Element-wise Multiplication:\n',E,'\n\n')
#matrix multiplication
F=np.dot(A,B)
print('Matrix Multiplication:\n',F,'\n\n')
A_trans=A.T
print('Transpose:\n',A_trans,'\n\n')

Addition:
 [[ 6  8]
 [10 12]] 


Subtraction:
 [[-4 -4]
 [-4 -4]] 


Element-wise Multiplication:
 [[ 5 12]
 [21 32]] 


Matrix Multiplication:
 [[19 22]
 [43 50]] 


Transpose:
 [[1 3]
 [2 4]] 


