In [1]:
import numpy as np
#matrix creation
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform svd
U,S,VT=np.linalg.svd(X)
#choose no. of components to keep
n_comp=2
#reconstruct matrix with reduced dimensions
X_reconstr=np.dot(U[:,:n_comp],np.dot(np.diag(S[:n_comp]),VT[:n_comp,:]))
print('Original Matrix\n',X,'\n\n')
print('Reconstructed Matrix\n',X_reconstr,'\n\n')

Original Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 




NameError: name 'X_reconstr' is not defined